# Site settings
theme: jekyll-theme-slate
title: Anurag Pande
email: anurag1212@cs.ucla.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my website. This is a bit about me.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anurag.github.io" # the base hostname & protocol for your site
github_username:  anurag1212

# Build settings
markdown: kramdown
